const {
    yellow: banana,
    blue: blueberry,
    red: cherror,
    red: cherry,
    magenta: grape,
    greenBright: lime,
    green: pear,
    magentaBright: plum,
    cyan: teal,
    bgYellow: bgBanana,
    bgBlue: bgBlueberry,
    bgRed: bgCherror,
    bgRed: bgCherry,
    bgMagenta: bgGrape,
    bgGreenBright: bgLime,
    bgGreen: bgPear,
    bgMagentaBright: bgPlum,
    bgCyan: bgTeal,
} = require('chalk');
const orange = require('chalk').hex('#FFA500');
const bgOrange = require('chalk').bgHex('#FFA500');

module.exports = {
    banana,
    blueberry,
    cherror,
    cherry,
    grape,
    lime,
    orange,
    pear,
    plum,
    teal,
    bgBanana,
    bgBlueberry,
    bgCherror,
    bgCherry,
    bgGrape,
    bgLime,
    bgOrange,
    bgPear,
    bgPlum,
    bgTeal,
};
